repos:
    - repo: https://github.com/psf/black
      rev: 22.3.0
      hooks:
          - id: black
            args: [".", --safe, --line-length=120]

    - repo: https://github.com/pre-commit/pre-commit-hooks
      rev: v3.2.0
      hooks:
          - id: trailing-whitespace
          - id: end-of-file-fixer
            language_version: python3

    - repo: local
      hooks:
          - id: lint
            name: isort
            entry: poetry run isort . --line-length=120
            language: system
            always_run: true
            pass_filenames: false
